name: Test MATSHA Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-toy-data:
    name: Run pipeline on toy data (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: matsha_env
        use-mamba: true

    - name: Install MATSHA in editable mode
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/test_pipeline_with_toy_data.py -v
