name: Test MATSHA Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-toy-data:
    name: Run pipeline on toy data
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: matsha_env
        environment-file: environment.yml
        auto-activate-base: false
        python-version: 3.12
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/test_pipeline_with_toy_data.py -v
