name: Test MATSHA Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-toy-data:
    name: Run pipeline on toy data
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up environment
      run: conda env create -f environment.yml
    
    - name: Activate environment
      shell: bash -l {0}
      run: |
        conda activate matsha_env
        pytest tests/test_pipeline_with_toy_data.py -v
